// criar uma produto na API
POST http://localhost:8080/node/produto HTTP/1.1
content-type: application/json

{
    "description": "Tomate",
    "value": "R$ 7,00"
}

###
// busca tds os produtos da API
GET http://localhost:8080/node/buscar-produtos HTTP/1.1
content-type: application/json

{}


###
// busca um produto da API, passando o id
GET http://localhost:8080/node/produto/2 HTTP/1.1
content-type: application/json
